title: Your Site Title
description: 
theme: jekyll-theme-minimal

# Exclude directories and/or files from the conversion
exclude:
  - node_modulesINFT 2202
  - assignment1
  - ice
  - package.json
  - package-lock.json
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
